Intimisi\KlientBundle\Entity\Pomoc:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    tytul:
      type: string
    opis:
      type: text
  lifecycleCallbacks: {  }
