imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        # entity_managers:
        #     default:
        #         mappings:
        #             KlientBundle: ~
        #             SonataUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    
fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Intimisi\UserBundle\Entity\User

    group:
        group_class: Intimisi\UserBundle\Entity\Group

services:
    admin.aktualnosci:
        class: Intimisi\KlientBundle\Admin\AktualnosciAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Notowania, label: Aktualności }
        arguments: [null, Intimisi\KlientBundle\Entity\Aktualnosci, SonataAdminBundle:CRUD]
    admin.notowania:
        class: Intimisi\KlientBundle\Admin\NotowaniaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Notowania, label: Notowania }
        arguments: [null, Intimisi\KlientBundle\Entity\Notowania, SonataAdminBundle:CRUD]

        
        
#    check_controller:
#        class: Intimisi\KlientBundle\Listener\CheckListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.controller , method: onCoreController }
#    before_loaded:
#        class: Intimisi\KlientBundle\Listener\CheckListener
#        arguments: ["@service_container"]
#        tags:
#            - { name: kernel.event_listener, event: kernel.controller, method: firstController }

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:
          
sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
        # role security information
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            OPERATOR: OPERATOR
            MASTER: MASTER
    title:      Panel Administracyjny
    title_logo: images/logo.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        dashboard: SonataAdminBundle:Core:dashboard.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

            # Customize this part to add new block configuration
            - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Witamy w Panelu Administracyjnym</h2> <p>Panel umożliwią prostą administrację <code>aktualnościami porfelu</code>, oraz zapewnia zarządzanie <code>użytkownikami systemu</code>.</p>:)"} }

sonata_user:
    security_acl:     false
    class:
        user:         Intimisi\UserBundle\Entity\User
        group:        Intimisi\UserBundle\Entity\Group