index:
    pattern:  /
    defaults: { _controller: UserBundle:Login:index }
    
login:
    pattern:  /login
    defaults: { _controller: UserBundle:Login:login }
    
login_check:
    pattern:   /login_check

logout:
    pattern:  /logout
    
register:
    pattern:  /register
    defaults: { _controller: UserBundle:Registration:register }

create:
    pattern:  /register/create
    defaults: { _controller: UserBundle:Registration:create }
    
sonata_user_impersonating: 
    pattern: /admin
    defaults: { _controller: SonataAdminBundle:Core:dashboard }
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile