<?php

namespace Intimisi\KlientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AktualnosciRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AktualnosciRepository extends EntityRepository
{
}