<?php

namespace Intimisi\KlientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UlubieniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UlubieniRepository extends EntityRepository
{
}